# Generated by Django 4.1.1 on 2022-09-15 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_menu_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='client',
            field=models.ManyToManyField(to='menu.client'),
        ),
    ]
