# Generated by Django 4.1.1 on 2022-09-15 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_menu_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='client',
        ),
    ]
